### ISSUE TITLE
IOwlGenerator not working properly when used second time on same graph.

### ISSUE THREAD

**Issue by trunksnair** [bpellens/owldotnetapi#3]
Hi,
I encountered a problem when i was trying to generate a file using the IOwlGenerator.
It gave correct result when used first time but the next time i use it in same program, the Edges have disappeared from the created file.
The code is like this:
    static void Main (string[] args)
            {
              IOwlParser parser = new OwlXmlParser();
              IOwlGraph graph = parser.ParseOwl("C://Users//Ramesh.Nair//Documents//OWl//oripizza.owl.xml");
            IOwlGenerator generator = new OwlXmlGenerator();
            **generator.GenerateOwl(graph, @"C:/SemWebPlugin/OPENPLANT/Convertor.owl.xml");**
           **generator.GenerateOwl(graph, @"C:/SemWebPlugin/OPENPLANT/Convertor.owl.xml");**
            }
        }
The nodes and edges are displayed First time but the next time only Nodes are diaplyed.

Thank you,
Regards
Ramesh Nair

**Comment by bpellens** [comment]
Hello,

Thank you very much for pointing this issue out to me. I just committed a quick fix for the serialization issue. The solution is not optimal but it should do it for now.
